[project]
name = "wa-bot-template"
version = "0.1.0"
description = "Template for WA bot using fastapi and uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.94",
    "fastapi[standard]>=0.115.6",
    "mangum>=0.19.0",
    "ngrok>=1.4.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.8.6",
]
