[tool.poetry]
name = "wa bot template"
version = "0.1.0"
description = "Template to create a WA bot using FastAPI framework"
authors = ["lautaropacella <lautaropacella@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
boto3 = "^1.35.92"
python-dotenv = "^1.0.1"
mangum = "^0.19.0"
requests = "^2.32.3"
ngrok = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
