[project]
name = "wa-bot-template"
version = "0.1.1"
description = "Template for WA bot using fastapi and uv"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.35.94",
    "fastapi[standard]>=0.115.6",
    "mangum>=0.19.0",
    "ngrok>=1.4.0",
    "nox>=2024.10.9",
    "pulumi-docker>=4.6.1",
    # "pulumi-awsx>=2.20.1",
    "pulumi-esc-sdk>=0.11.0",
    "pulumi-gcp>=8.14.0",
    "pulumi-random>=4.16.8",
    "requests>=2.32.3",
    "uv>=0.5.19",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "darglint>=1.8.1",
    "isort>=5.13.2",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]

[tool.uv]
preview = true
default-groups = ["dev"]
managed = true
