[project]
name = "wa-bot-template"
version = "0.1.1"
description = "Template for WA bot using fastapi and uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.94",
    "fastapi[standard]>=0.115.6",
    "mangum>=0.19.0",
    "ngrok>=1.4.0",
    "nox>=2024.10.9",
    "pulumi>=3.145.0",
    "pulumi-aws>=6.66.3",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "darglint>=1.8.1",
    "isort>=5.13.2",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.8.6",
    # "wa-bot-template",
]

[tool.uv.sources]
wa-bot-template = { workspace = true }
