name: kitsune
description: A Python program to deploy a virtual machine on Amazon EC2 and Docker container deployment
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: vm-aws-python
