name: CI/CD Pipeline

on:
  workflow_dispatch:

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  PULUMI_STACK_NAME: dev
  GCP_REGION: us-central1
  AWS_REGION: us-east-1
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  OICD_AWS_GH_ACTIONS: ${{ secrets.OICD_AWS_GH_ACTIONS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build & Sync Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          prune-cache: false
          ignore-nothing-to-cache: true
      - name: Sync the dependencies from the pyproject.toml
        run: uv sync --all-groups --dev
      - name: Lint code with Ruff using Nox
        run: uv run nox -s lint
      - name: Check code formatting with Ruff using Nox
        run: uv run nox -s fmt

  tests:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: Sync the dependencies from the pyproject.toml
        run: uv sync --all-extras --dev
      - name: Run tests with pytest
        run: uv run nox -s tests

  deploy:
    name: Pulumi Deploy
    needs: [tests, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          pyproject-file: "pyproject.toml"
      - name: Sync uv dependencies
        run: uv sync --all-extras --dev
      - name: Setup Cloud Provider [GCP]
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Setup Cloud Provider [AWS]
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OICD_AWS_GH_ACTIONS }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Pulumi Up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          upsert: true
          refresh: true
          work-dir: infra/
          comment-on-summary: true
          diff: true
