name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
  PULUMI_STACK_NAME: dev

jobs:
  build:
    name: Build & Sync Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          # uncomment add more python versions here
          # - "3.12"
          # - "3.13"

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Sync the dependencies from the pyproject.toml
        run: uv sync --all-extras --dev
      - name: Lint code with Ruff
        run: uvx ruff check --fix --output-format=github --target-version=py312
      - name: Check code formatting with Ruff
        run: uvx ruff format -q --diff --target-version=py312
        continue-on-error: true

  test:
    name: Test Suite
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run the tests
        run: uv run pytest --cov=app
  
  deploy:
    name: Pulumi Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Change directory
        run: cd infra/

      - uses: pulumi/actions@v6
        with:
          command: up
          upsert: true
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
          PULUMI_STACK_NAME: ${{ env.PULUMI_STACK_NAME }}