name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Sync Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          # add more python versions here
          # - "3.13"

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Sync the dependencies from the pyproject.toml
        run: uv sync --all-extras --dev
      - name: Lint code with Ruff
        run: ruff check --fix --output-format=github --target-version=py312
      - name: Check code formatting with Ruff
        run: ruff format -q --diff --target-version=py312
        continue-on-error: true

  test:
    name: Test Suite
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run the tests
        run: uv run pytest --cov=app

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh
      - name: Authenticate with Pulumi Service
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Deploy using Pulumi
        run: pulumi up --yes